Ce document montre que la FAO n'a pas de données importable pour le moment, et explique donc notre utilisation de ces données via un fichier CSV plus direct. Le package FAOSTAT est inutilisable pour le moment.

Commençons par importer les packages nécessaire

In [1]:
import pandas as pd
import faostat

Voici l'ensemble des types de données que possède la FAO :

In [12]:
df = faostat.list_datasets_df()
df

,code,label,date_update,note_update,release_current,state_current,year_current,release_next,state_next,year_next
0,QCL,Crops and livestock products,2024-10-07,minor revision,2023-12-23 / 2024-10-07,final,2022,2024-12,final,2023
1,QI,Production Indices,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
2,QV,Value of Agricultural Production,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
3,FS,Suite of Food Security Indicators,2024-07-25,minor revision,2024-07-24 / 2024-07-25,final,2023,2025-07,final,2024
4,FBS,Food Balances (2010-),2024-07-19,,2024-07-19,final,2022,2025-07,final,2023
...,...,...,...,...,...,...,...,...,...,...
61,FA,Food Aid Shipments (WFP),2016-12-22,,2016-12-22,preliminary,2016,,,
62,RM,Machinery,2021-12-03,minor revision,2011-12-22 / 2021-12-03,final,2009,,,
63,RY,Machinery Archive,2021-12-03,minor revision,2006-12-31 / 2021-12-03,final,2005,,,
64,RA,Fertilizers archive,2020-09-08,minor revision,2013-12-31 / 2020-09-08,final,2002,,,
65,PA,Producer Prices (old series),1991-12-31,,1991-12-31,final,1990,,,

Nous remarquons alors (et grâce au site de la FAO) que les données qui nous intéresse pour la déforestation sont celles codé "FO" (ligne 54), soit "Forestry Production and Trade"

In [14]:
clair = pd.DataFrame(faostat.list_pars(code="FO"))
clair

,0,1,2
0,parameter code,coding_systems,subdimensions {code: meaning}
1,area,"[M49, FAO, ISO2, ISO3]","{'countries': 'Countries', 'regions': 'Regions..."
2,element,[],{'elements': 'Elements'}
3,item,[],"{'items': 'Items', 'itemsagg': 'Items Aggregat..."
4,year,[],{'years': 'Years'}

Nous voyons donc qu'il y a 4 éléments important à retirer pour le code FO : "area", "element", "item" et "year"

In [15]:
faostat.get_items(code="FO")

{'Wood fuel, coniferous': '1627',
 'Wood fuel, non-coniferous': '1628',
 'Wood fuel, all species (export/import, 1961-2016)': '1629',
 'Industrial roundwood, coniferous (export/import)': '1651',
 'Industrial roundwood, non-coniferous tropical (export/import)': '1657',
 'Industrial roundwood, non-coniferous non-tropical (export/import)': '1670',
 'Sawlogs and veneer logs, coniferous': '1601',
 'Sawlogs and veneer logs, non-coniferous': '1604',
 'Pulpwood, round and split, coniferous (production)': '1602',
 'Pulpwood, round and split, non-coniferous (production)': '1603',
 'Pulpwood, round and split, all species (export/import, 1961-1989)': '1614',
 'Pulpwood and particles, coniferous (production, 1961-1997)': '1608',
 'Pulpwood and particles, non-coniferous (production, 1961-1997)': '1611',
 'Other industrial roundwood, coniferous (production)': '1623',
 'Other industrial roundwood, non-coniferous (production)': '1626',
 'Other industrial roundwood, all species (export/import, 1961-1989)': '1625',
 'Wood charcoal': '1630',
 'Wood chips and particles': '1619',
 'Wood residues': '1620',
 'Recovered post-consumer wood': '1600',
 'Wood pellets': '1693',
 'Wood briquettes and other agglomerates': '1694',
 'Sawnwood, coniferous': '1632',
 'Sawnwood, non-coniferous all': '1633',
 'Veneer sheets': '1634',
 'Plywood': '1640',
 'Particle board and OSB (1961-1994)': '1646',
 'Particle board': '1697',
 'OSB': '1606',
 'Hardboard': '1647',
 'MDF/HDF': '1648',
 'Other fibreboard': '1650',
 'Fibreboard, compressed (1961-1994)': '1649',
 'Mechanical and semi-chemical wood pulp': '1685',
 'Mechanical wood pulp': '1654',
 'Semi-chemical wood pulp': '1655',
 'Chemical wood pulp': '1656',
 'Chemical wood pulp, sulphate, unbleached': '1662',
 'Chemical wood pulp, sulphate, bleached': '1663',
 'Chemical wood pulp, sulphite': '1686',
 'Chemical wood pulp, sulphite, unbleached': '1660',
 'Chemical wood pulp, sulphite, bleached': '1661',
 'Dissolving wood pulp': '1667',
 'Pulp from fibres other than wood': '1668',
 'Recovered fibre pulp': '1609',
 'Recovered paper': '1669',
 'Newsprint': '1671',
 'Printing and writing papers': '1674',
 'Printing and writing papers, uncoated, mechanical': '1612',
 'Printing and writing papers, uncoated, wood free': '1615',
 'Printing and writing papers, coated': '1616',
 'Other paper and paperboard': '1675',
 'Household and sanitary papers': '1676',
 'Wrapping and packaging paper and paperboard (1961-1997)': '1681',
 'Case materials': '1617',
 'Cartonboard': '1618',
 'Wrapping papers': '1621',
 'Other papers mainly for packaging': '1622',
 'Other paper and paperboard n.e.s. (not elsewhere specified)': '1683'}

In [17]:
faostat.get_elements(code="FO")

{'Production Quantity': '2510',
 'Import Quantity': '2610',
 'Import Value': '2620',
 'Export Quantity': '2910',
 'Export Value': '2920'}

In [27]:
faostat.get_years(code="FO")

{'2022': '2022',
 '2021': '2021',
 '2020': '2020',
 '2019': '2019',
 '2018': '2018',
 '2017': '2017',
 '2016': '2016',
 '2015': '2015',
 '2014': '2014',
 '2013': '2013',
 '2012': '2012',
 '2011': '2011',
 '2010': '2010',
 '2009': '2009',
 '2008': '2008',
 '2007': '2007',
 '2006': '2006',
 '2005': '2005',
 '2004': '2004',
 '2003': '2003',
 '2002': '2002',
 '2001': '2001',
 '2000': '2000',
 '1999': '1999',
 '1998': '1998',
 '1997': '1997',
 '1996': '1996',
 '1995': '1995',
 '1994': '1994',
 '1993': '1993',
 '1992': '1992',
 '1991': '1991',
 '1990': '1990',
 '1989': '1989',
 '1988': '1988',
 '1987': '1987',
 '1986': '1986',
 '1985': '1985',
 '1984': '1984',
 '1983': '1983',
 '1982': '1982',
 '1981': '1981',
 '1980': '1980',
 '1979': '1979',
 '1978': '1978',
 '1977': '1977',
 '1976': '1976',
 '1975': '1975',
 '1974': '1974',
 '1973': '1973',
 '1972': '1972',
 '1971': '1971',
 '1970': '1970',
 '1969': '1969',
 '1968': '1968',
 '1967': '1967',
 '1966': '1966',
 '1965': '1965',
 '1964': '1964',
 '1963': '1963',
 '1962': '1962',
 '1961': '1961'}

In [20]:
faostat.get_par_df("FO","area")

                                                 label   code aggregate_type
0                                          Afghanistan      2              0
1                                              Albania      3              0
2                                              Algeria      4              0
3                                       American Samoa      5              0
4                                              Andorra      6              0
..                                                 ...    ...            ...
315            Small Island Developing States > (List)  5803>              >
316        Low Income Food Deficit Countries + (Total)   5815              +
317         Low Income Food Deficit Countries > (List)  5815>              >
318  Net Food Importing Developing Countries + (Total)   5817              +
319   Net Food Importing Developing Countries > (List)  5817>              >

[320 rows x 3 columns]

Ainsi, nous voyons les charactéristiques qu'ils nous faut. Cependant :

In [2]:
mypars = {'area': "004",
              'element': "5516",
              'item': "1627",
              'year': "1963"}
data = faostat.get_data_df(code='FO', pars=mypars, strval=False)
data

Empty DataFrame
Columns: [Domain Code, Domain, Area Code, Area, Element Code, Element, Item Code, Item, Year Code, Year, Unit, Value]
Index: []

Comme nous pouvons le remarquer, les données sont entièrement vide - et nous pouvons facilement vérifier sur le site de la FAO que ces données existent bien, mais sont simplement complétement inaccessibles via l'API (et donc cette extension) actuellement. Cela vaut quel que soit les paramètres demandés tant l'API a été laissé à l'abandon par la FAO.

Ceci explique donc pourquoi nous n'allons pas utiliser l'API ni l'extension FAOSTAT, et à la place utiliser un fichier CSV que nous allons traiter directement.