Package nécessaire

In [ ]:
import pandas as pd
import faostat

In [17]:
df = faostat.list_datasets_df()
df

,code,label,date_update,note_update,release_current,state_current,year_current,release_next,state_next,year_next
0,QCL,Crops and livestock products,2024-10-07,minor revision,2023-12-23 / 2024-10-07,final,2022,2024-12,final,2023
1,QI,Production Indices,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
2,QV,Value of Agricultural Production,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
3,FS,Suite of Food Security Indicators,2024-07-25,minor revision,2024-07-24 / 2024-07-25,final,2023,2025-07,final,2024
4,FBS,Food Balances (2010-),2024-07-19,,2024-07-19,final,2022,2025-07,final,2023
...,...,...,...,...,...,...,...,...,...,...
61,FA,Food Aid Shipments (WFP),2016-12-22,,2016-12-22,preliminary,2016,,,
62,RM,Machinery,2021-12-03,minor revision,2011-12-22 / 2021-12-03,final,2009,,,
63,RY,Machinery Archive,2021-12-03,minor revision,2006-12-31 / 2021-12-03,final,2005,,,
64,RA,Fertilizers archive,2020-09-08,minor revision,2013-12-31 / 2020-09-08,final,2002,,,
65,PA,Producer Prices (old series),1991-12-31,,1991-12-31,final,1990,,,

Nous remarquons alors (et grâce au site de la FAO) que les données qui nous intéresse pour la déforestation sont celles codé "FO" (ligne 54), soit "Forestry Production and Trade"

In [18]:
clair = pd.DataFrame(faostat.list_pars(code="FO"))
clair

,0,1,2
0,parameter code,coding_systems,subdimensions {code: meaning}
1,area,"[M49, FAO, ISO2, ISO3]","{'countries': 'Countries', 'regions': 'Regions..."
2,element,[],{'elements': 'Elements'}
3,item,[],"{'items': 'Items', 'itemsagg': 'Items Aggregat..."
4,year,[],{'years': 'Years'}

Nous voyons donc que les

In [19]:
mypars = {'area': [2, 4000],
              'element': [2312, 2313],
              'item': '221',
              'year': [2020, 2021]}
data = faostat.get_data_df('FO', pars=mypars, strval=True)
df

,code,label,date_update,note_update,release_current,state_current,year_current,release_next,state_next,year_next
0,QCL,Crops and livestock products,2024-10-07,minor revision,2023-12-23 / 2024-10-07,final,2022,2024-12,final,2023
1,QI,Production Indices,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
2,QV,Value of Agricultural Production,2024-03-13,,2024-03-13,final,2022,2024-12,final,2023
3,FS,Suite of Food Security Indicators,2024-07-25,minor revision,2024-07-24 / 2024-07-25,final,2023,2025-07,final,2024
4,FBS,Food Balances (2010-),2024-07-19,,2024-07-19,final,2022,2025-07,final,2023
...,...,...,...,...,...,...,...,...,...,...
61,FA,Food Aid Shipments (WFP),2016-12-22,,2016-12-22,preliminary,2016,,,
62,RM,Machinery,2021-12-03,minor revision,2011-12-22 / 2021-12-03,final,2009,,,
63,RY,Machinery Archive,2021-12-03,minor revision,2006-12-31 / 2021-12-03,final,2005,,,
64,RA,Fertilizers archive,2020-09-08,minor revision,2013-12-31 / 2020-09-08,final,2002,,,
65,PA,Producer Prices (old series),1991-12-31,,1991-12-31,final,1990,,,

In [20]:
faostat.get_par_df("FO","area")

                                                 label   code aggregate_type
0                                          Afghanistan      2              0
1                                              Albania      3              0
2                                              Algeria      4              0
3                                       American Samoa      5              0
4                                              Andorra      6              0
..                                                 ...    ...            ...
315            Small Island Developing States > (List)  5803>              >
316        Low Income Food Deficit Countries + (Total)   5815              +
317         Low Income Food Deficit Countries > (List)  5815>              >
318  Net Food Importing Developing Countries + (Total)   5817              +
319   Net Food Importing Developing Countries > (List)  5817>              >

[320 rows x 3 columns]

Nous allons ensuite devoir traiter les données. Pour y voir plus clair, nous allons créer un dataframe où une colonne correspond à un type de données (au lieu d'une seule colonne avec un vecteur). Pour cela, nous allons installer le package suivant :

In [21]:
%pip install ast

Collecting ast
  Using cached AST-0.0.2.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\phili\AppData\Local\Temp\pip-install-ka3lf62m\ast_8f65fc55d1cf4428bfd4b6f4c606a304\setup.py", line 6, in <module>
          README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
        File "c:\Users\phili\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\phili\\AppData\\Local\\Temp\\pip-install-ka3lf62m\\ast_8f65fc55d1cf4428bfd4b6f4c606a304\\AST/README'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Puis nous allons transformer "clair" en un dataframe plus lisible.

In [22]:
import pandas as pd
import ast
import re

# Fonction pour nettoyer les données
def clean_subdimensions(value):
    if isinstance(value, str):  # Si la valeur est une chaîne
        match = re.match(r"subdimensions\s+\{(.*)\}", value)
        if match:
            content = match.group(1)
            pairs = [item.split(":") for item in content.split(",")]
            return {k.strip(): v.strip() for k, v in pairs}
        else:
            # Essayer de convertir avec ast.literal_eval si applicable
            try:
                return ast.literal_eval(value)
            except (ValueError, SyntaxError):
                return None
    elif isinstance(value, dict):  # Si la valeur est déjà un dict
        return value
    return None  # Si le type n'est pas géré

# Appliquer la fonction de nettoyage
clair[2] = clair[2].apply(clean_subdimensions)

# Normaliser la colonne 2
subdimensions_df = pd.json_normalize(clair[2])

# Fusionner avec le DataFrame original
clair_df = pd.concat([clair.drop(columns=[2]), subdimensions_df], axis=1)

# Afficher le résultat
clair_df

,0,1,code,countries,regions,specialgroups,elements,items,itemsagg,years
0,parameter code,coding_systems,meaning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,area,"[M49, FAO, ISO2, ISO3]",NaN,Countries,Regions,Special Groups,NaN,NaN,NaN,NaN
2,element,[],NaN,NaN,NaN,NaN,Elements,NaN,NaN,NaN
3,item,[],NaN,NaN,NaN,NaN,NaN,Items,Items Aggregated,NaN
4,year,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,Years